<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python_DataAnalysis(NumPy)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#4.1.1

In [0]:
import numpy as np
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3,)

In [0]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
type(b)

numpy.ndarray

In [11]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape(2, 3)
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [13]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [14]:
a.dtype

dtype('int64')

In [15]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [16]:
d.dtype

dtype('int16')

In [17]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [18]:
a

array([1, 2, 3])

In [19]:
a[0]

1

In [20]:
a[1:]

array([2, 3])

In [21]:
a[-1]

3

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b[0]

array([1, 2, 3])

In [24]:
b[1, 0]

4

In [25]:
b[:, 2]

array([3, 6])

In [26]:
b[1, :]

array([4, 5, 6])

In [27]:
b[0, 1:]

array([2, 3])

In [28]:
b[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [29]:
a

array([1, 2, 3])

In [30]:
a[2] = 4
a

array([1, 2, 4])

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [33]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [34]:
a1 = a
a1

array([1, 2, 4])

In [35]:
a1[1] = 5
a1

array([1, 5, 4])

In [36]:
a

array([1, 5, 4])

In [37]:
a2 = a.copy()
a2

array([1, 5, 4])

In [38]:
a2[0] = 6
a2

array([6, 5, 4])

In [39]:
a

array([1, 5, 4])

In [40]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c3 = c2.ravel()
c4 = c2.flatten()

In [0]:
c3[0] =6
c4[1] =7

In [47]:
c4[1]

7

In [48]:
c3

array([6, 1, 2, 3, 4, 5])

In [49]:
c4

array([0, 7, 2, 3, 4, 5])

In [51]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [53]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [56]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array1[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [64]:
f = np.random.random((3, 2))
f

array([[0.98691191, 0.5256733 ],
       [0.06531839, 0.00457094],
       [0.27614568, 0.92469079]])

In [65]:
print(f)

[[0.98691191 0.5256733 ]
 [0.06531839 0.00457094]
 [0.27614568 0.92469079]]


In [69]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])