<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python_DataAnalysis(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**4.1.2 NumPyの概要**

In [0]:
import numpy as np
a = np.array([1, 2, 3])

In [173]:
a

array([1, 2, 3])

In [174]:
print(a)

[1 2 3]


In [175]:
type(a)

numpy.ndarray

In [176]:
a.shape

(3,)

In [0]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [178]:
b.shape

(2, 3)

In [179]:
type(b)

numpy.ndarray

In [180]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape(2, 3)
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [181]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [182]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [183]:
a.dtype

dtype('int64')

In [184]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [185]:
d.dtype

dtype('int16')

In [186]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [187]:
a

array([1, 2, 3])

In [188]:
a[0]

1

In [189]:
a[1:]

array([2, 3])

In [190]:
a[-1]

3

In [191]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [192]:
b[0]

array([1, 2, 3])

In [193]:
b[1, 0]

4

In [194]:
b[:, 2]

array([3, 6])

In [195]:
b[1, :]

array([4, 5, 6])

In [196]:
b[0, 1:]

array([2, 3])

In [197]:
b[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [198]:
a

array([1, 2, 3])

In [199]:
a[2] = 4
a

array([1, 2, 4])

In [200]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [202]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [203]:
a1 = a
a1

array([1, 2, 4])

In [204]:
a1[1] = 5
a1

array([1, 5, 4])

In [205]:
a

array([1, 5, 4])

In [206]:
a2 = a.copy()
a2

array([1, 5, 4])

In [207]:
a2[0] = 6
a2

array([6, 5, 4])

In [208]:
a

array([1, 5, 4])

In [209]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c3 = c2.ravel()
c4 = c2.flatten()

In [0]:
c3[0] =6
c4[1] =7

In [212]:
c4[1]

7

In [213]:
c3

array([6, 1, 2, 3, 4, 5])

In [214]:
c4

array([0, 7, 2, 3, 4, 5])

In [215]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [216]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [217]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array1[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [218]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [220]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [221]:
f = np.random.random((3, 2))
print(f)

[[0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]


In [222]:
print(f)

[[0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]


In [223]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [224]:
np.random.seed(123)
np.random.random((4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [225]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [226]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [227]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [228]:
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2, 3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [229]:
np.random.seed(123)
np.random.uniform(size=(4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [230]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [231]:
np.zeros(3)

array([0., 0., 0.])

In [232]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [233]:
np.ones(2)

array([1., 1.])

In [234]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [235]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [236]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [237]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [238]:
np.nan

nan

In [239]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [240]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [241]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [242]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [243]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [244]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [245]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [246]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [247]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [248]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

**4.1.3 NumPyの各機能**

In [249]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2,3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print('a' , a)
print('b' , b)
print('c' , c)
print('d' , d)
print('e' , e)

a [0 1 2]
b [[-3 -2 -1]
 [ 0  1  2]]
c [[1 2 3]
 [4 5 6]]
d [[0 1]
 [2 3]
 [4 5]]
e [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [250]:
print('a:', a.shape)
print('b:', b.shape)
print('c:', c.shape)
print('d:', d.shape)
print('e:', e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [251]:
li = [[-3, -2, -1], 
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
  new.append([])
  for k in j:
    new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [252]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [253]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [254]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [255]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [256]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [257]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [258]:
a

array([0, 1, 2])

In [259]:
a + 10

array([10, 11, 12])

In [260]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [261]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [262]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [263]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [264]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [265]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [266]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [267]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [268]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [269]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])