<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python_DataAnalysis(NumPy)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**4.1.2 NumPyの概要**

In [0]:
import numpy as np
a = np.array([1, 2, 3])

In [0]:
a

array([1, 2, 3])

In [0]:
print(a)

[1 2 3]


In [0]:
type(a)

numpy.ndarray

In [0]:
a.shape

(3,)

In [0]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [0]:
b.shape

(2, 3)

In [0]:
type(b)

numpy.ndarray

In [0]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape(2, 3)
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [0]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [0]:
a.dtype

dtype('int64')

In [0]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [0]:
d.dtype

dtype('int16')

In [0]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [0]:
a

array([1, 2, 3])

In [0]:
a[0]

1

In [0]:
a[1:]

array([2, 3])

In [0]:
a[-1]

3

In [0]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
b[0]

array([1, 2, 3])

In [0]:
b[1, 0]

4

In [0]:
b[:, 2]

array([3, 6])

In [0]:
b[1, :]

array([4, 5, 6])

In [0]:
b[0, 1:]

array([2, 3])

In [0]:
b[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [0]:
a

array([1, 2, 3])

In [0]:
a[2] = 4
a

array([1, 2, 4])

In [0]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [0]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [0]:
a1 = a
a1

array([1, 2, 4])

In [0]:
a1[1] = 5
a1

array([1, 5, 4])

In [0]:
a

array([1, 5, 4])

In [0]:
a2 = a.copy()
a2

array([1, 5, 4])

In [0]:
a2[0] = 6
a2

array([6, 5, 4])

In [0]:
a

array([1, 5, 4])

In [0]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c3 = c2.ravel()
c4 = c2.flatten()

In [0]:
c3[0] =6
c4[1] =7

In [0]:
c4[1]

7

In [0]:
c3

array([6, 1, 2, 3, 4, 5])

In [0]:
c4

array([0, 7, 2, 3, 4, 5])

In [0]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [0]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [0]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array1[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [0]:
f = np.random.random((3, 2))
print(f)

[[0.43857224 0.0596779 ]
 [0.39804426 0.73799541]
 [0.18249173 0.17545176]]


In [0]:
print(f)

[[0.98691191 0.5256733 ]
 [0.06531839 0.00457094]
 [0.27614568 0.92469079]]


In [0]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [0]:
np.random.seed(123)
np.random.random((4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [0]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [0]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [0]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [0]:
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2, 3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [0]:
np.random.seed(123)
np.random.uniform(size=(4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [0]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(2)

array([1., 1.])

In [0]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [0]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [0]:
np.nan

nan

In [0]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [0]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [0]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [0]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [0]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [0]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [0]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [0]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [0]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

**4.1.3 NumPyの各機能**

In [102]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2,3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 11, 10)
print('a' , a)
print('b' , b)
print('c' , c)
print('d' , d)
print('e' , e)

a [0 1 2]
b [[-3 -2 -1]
 [ 0  1  2]]
c [[1 2 3]
 [4 5 6]]
d [[0 1]
 [2 3]
 [4 5]]
e [-1.          0.33333333  1.66666667  3.          4.33333333  5.66666667
  7.          8.33333333  9.66666667 11.        ]
