<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python%E9%80%9F%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

メモを取ることができます

＃変数

# 変数

## 数値

In [0]:
a = 1

In [0]:
print(a)

1


In [0]:
a

1

In [0]:
b = 1.5

In [0]:
b

1.5

In [0]:
type(a) #integer:整数

int

In [0]:
type(b) #float:実数

float

## 文字列

In [0]:
name = 'キカガク'

In [0]:
name

'キカガク'

In [0]:
name1 = '株式会社'

In [0]:
name2 = 'キカガク'

In [0]:
name1+ name2 #String:文字列

'株式会社キカガク'

In [0]:
a + name1 #整数と文字列は足し算ができない

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## 数値の四則演算

In [0]:
1 + 1

2

In [0]:
2 - 1

1

In [0]:
3 * 5

15

In [0]:
10 / 2

5.0

In [0]:
2 ** 3

8

# 基本構文

## 比較演算

In [0]:
1 < 2

True

In [0]:
a = 3

In [0]:
a < 2

False

In [0]:
a == 3 #等しい

True

In [0]:
a == 4

False

In [0]:
a != 3 #等しくない

False

In [0]:
a != 4

True

## エスケープシーケンス

In [0]:
print('私はキカガクです。\nよろしくお願いします。')

私はキカガクです。
よろしくお願いします。


In [0]:
print('私はキカガクです。\nよろしくお願いします。\n\tタブ1\n\tタブ2')

私はキカガクです。
よろしくお願いします。
	タブ1
	タブ2


## コメントアウト

In [0]:
# これは○○な機能です。

## リスト

In [0]:
numbers = [4, 5, 6, 7]

In [0]:
numbers

[4, 5, 6, 7]

In [0]:
numbers[0] = 10

In [0]:
numbers

[10, 5, 6, 7]

In [0]:
words = ['hello', 'world', 1, 3.2]

In [0]:
names = [] #からのリスト

In [0]:
names

[]

In [0]:
names.append('株式会社')

In [0]:
names

['株式会社']

In [0]:
names.append('キカガク')

In [0]:
names

['株式会社', 'キカガク']

# タプル

In [0]:
t = (4, 5, 6 , 7) #タプルの定義:()

In [0]:
t

(4, 5, 6, 7)

In [0]:
t[0]

4

In [0]:
t[0:3]

(4, 5, 6)

In [0]:
t[0]=10

TypeError: 'tuple' object does not support item assignment

# 辞書

In [0]:
results = {'数学':90, '理科':80, '英語':75}

In [0]:
results['数学']

90

# 制御構文

## for文:繰り返し

In [0]:
for i in range(5):
    print(i)
    print('キカガク')

0
キカガク
1
キカガク
2
キカガク
3
キカガク
4
キカガク


In [0]:
names = ['佐藤', '鈴木', '高橋' ,'吉田', '吉崎']
for i in range(3):
    print(i)

0
1
2


In [0]:
for i in range(len(names)):
    print(names[i] + 'さん')

佐藤さん
鈴木さん
高橋さん
吉田さん
吉崎さん


In [0]:
len(names) #length

5

In [0]:
for name in names:
    print(name + 'さん')

佐藤さん
鈴木さん
高橋さん
吉田さん
吉崎さん


## if文：条件分岐

In [0]:
val = 0
if val > 0:
    print('正の値です')
elif val == 0:
    print('0です')
else:
    print('負の値です')

0です


## 関数

## 一番簡単な関数

In [0]:
# define:定義する
def say_hello():
    print('こんにちは、キカガクさん')
    print('ご機嫌いかがですか。')

In [0]:
say_hello()

こんにちは、キカガクさん
ご機嫌いかがですか。


## 入力(引数)のある関数

In [0]:
#name:引数
def say_hello2(name):
    print('こんにちは' + name + 'さん')
    print('ご機嫌いかがですか。')

In [0]:
#使う
say_hello2("株式会社キカガク")

こんにちは株式会社キカガクさん
ご機嫌いかがですか。


## 出力(返り値)のある関数

In [0]:
def add(a, b, c):
    return a + b + c

In [0]:
result = add(3, 5, 10)

In [0]:
result

18

## 実践課題
絶対値を返す関数 absを作ってください。

出力のイメージ

-abs(-1) ->1
-abs(-5.2) ->5.2
-abs(3 -> 3

In [0]:
def abs(num):
    if num < 0:
        return -1*num
    else:
        return num

In [0]:
abs(-19)

19

In [0]:
abs(99)

99

In [0]:
abs(-123)

123

## Numpy:数値計算

In [0]:
import numpy as np

In [0]:
#ベクトルの定義
x = np.array([1, 2, 3])

In [0]:
x

array([1, 2, 3])

In [0]:
y = np.array([2, 3.9, 6.1])

In [0]:
y

array([2. , 3.9, 6.1])

## データの中心化

In [0]:
#平均の算出
x.mean()

2.0

In [0]:
y.mean()

4.0

In [0]:
#中心化
xc = x - x.mean()

In [0]:
xc

array([-1.,  0.,  1.])

In [0]:
yc = y - y.mean()

In [0]:
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [0]:
#要素ごとの掛け算(要素積)
xx =xc * xc

In [0]:
xx

array([1., 0., 1.])

In [0]:
xc

array([-1.,  0.,  1.])

In [0]:
xy = xc * yc

In [0]:
xx.sum()

2.0

In [0]:
xy.sum()

4.1

In [0]:
a = xy.sum() / xx.sum()

In [0]:
a

2.05

In [0]:
%pwd

'C:\\Users\\hatec'

In [0]:
%cd

C:\Users\hatec


In [0]:
%pwd

'C:\\Users\\hatec'

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('original.csv')
df

x         y
0   40.362  137500.0
1   40.686  132500.0
2   38.430   93000.0
3   36.822   96500.0
4   37.002  100500.0
5   35.106   97500.0
6   35.016   97500.0
7   36.762  102000.0
8   38.844   99000.0
9   37.374   97000.0
10  37.170  108500.0
11  40.290  114000.0
12  35.478   94000.0
13  36.552   93500.0
14  37.524   92500.0
15  35.568   91500.0
16  37.056  106000.0
17  36.126   96000.0
18  35.232  102000.0
19  34.386   96500.0
20  35.220  110000.0
21  36.024  101500.0
22  35.766  102500.0
23  35.136   86500.0
24  35.274   94000.0
25  35.916  107000.0
26  33.678   78500.0
27  34.158   81000.0
28  38.586   90000.0
29  33.822   71500.0
..     ...       ...
70  35.250   87000.0
71  35.280   95500.0
72  33.432  115500.0
73  38.496  118000.0
74  35.154  113000.0
75  39.276  147000.0
76  36.120  116000.0
77  37.890  123000.0
78  41.160  149500.0
79  41.880  186000.0
80  46.590  199000.0
81  36.864  181000.0
82  42.930  189500.0
83  39.378  162500.0
84  33.624  132000.0
85  36.918  148000.0
86  46.986  250000.0
87  40.692  160000.0
88  39.336  149000.0
89  43.110  174500.0
90  41.706  185000.0
91  40.434  152500.0
92  43.068  182000.0
93  40.800  155500.0
94  39.624  145500.0
95  47.250  250000.0
96  43.722  166500.0
97  42.642  151500.0
98  43.644  173000.0
99  41.850  174500.0

[100 rows x 2 columns]

In [0]:
df.head(3)

x         y
0  40.362  137500.0
1  40.686  132500.0
2  38.430   93000.0

In [0]:
#データの抽出
x = df['x']
y = df['y']

In [0]:
x

0     40.362
1     40.686
2     38.430
3     36.822
4     37.002
5     35.106
6     35.016
7     36.762
8     38.844
9     37.374
10    37.170
11    40.290
12    35.478
13    36.552
14    37.524
15    35.568
16    37.056
17    36.126
18    35.232
19    34.386
20    35.220
21    36.024
22    35.766
23    35.136
24    35.274
25    35.916
26    33.678
27    34.158
28    38.586
29    33.822
       ...  
70    35.250
71    35.280
72    33.432
73    38.496
74    35.154
75    39.276
76    36.120
77    37.890
78    41.160
79    41.880
80    46.590
81    36.864
82    42.930
83    39.378
84    33.624
85    36.918
86    46.986
87    40.692
88    39.336
89    43.110
90    41.706
91    40.434
92    43.068
93    40.800
94    39.624
95    47.250
96    43.722
97    42.642
98    43.644
99    41.850
Name: x, Length: 100, dtype: float64

In [0]:
y

0     137500.0
1     132500.0
2      93000.0
3      96500.0
4     100500.0
5      97500.0
6      97500.0
7     102000.0
8      99000.0
9      97000.0
10    108500.0
11    114000.0
12     94000.0
13     93500.0
14     92500.0
15     91500.0
16    106000.0
17     96000.0
18    102000.0
19     96500.0
20    110000.0
21    101500.0
22    102500.0
23     86500.0
24     94000.0
25    107000.0
26     78500.0
27     81000.0
28     90000.0
29     71500.0
        ...   
70     87000.0
71     95500.0
72    115500.0
73    118000.0
74    113000.0
75    147000.0
76    116000.0
77    123000.0
78    149500.0
79    186000.0
80    199000.0
81    181000.0
82    189500.0
83    162500.0
84    132000.0
85    148000.0
86    250000.0
87    160000.0
88    149000.0
89    174500.0
90    185000.0
91    152500.0
92    182000.0
93    155500.0
94    145500.0
95    250000.0
96    166500.0
97    151500.0
98    173000.0
99    174500.0
Name: y, Length: 100, dtype: float64

# Matplotlib:グラフの描画

In [0]:
import matplotlib.pyplot as plt

In [1]:
#横軸をx,縦軸をyの散布図(scatter)をプロット
plt.scattter(x, y)

NameError: ignored