<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python_DataAnalysis(NumPy)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#4.1.1

In [0]:
import numpy as np
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [0]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [14]:
type(b)

numpy.ndarray

In [17]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape(2, 3)
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [20]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [21]:
a.dtype

dtype('int64')

In [25]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [26]:
d.dtype

dtype('int16')

In [27]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [28]:
a

array([1, 2, 3])

In [29]:
a[0]

1

In [30]:
a[1:]

array([2, 3])

In [33]:
a[-1]

3

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b[0]

array([1, 2, 3])

In [37]:
b[1, 0]

4

In [39]:
b[:, 2]

array([3, 6])

In [40]:
b[1, :]

array([4, 5, 6])

In [41]:
b[0, 1:]

array([2, 3])

In [42]:
b[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [43]:
a

array([1, 2, 3])

In [44]:
a[2] = 4
a

array([1, 2, 4])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [48]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [49]:
a1 = a
a1

array([1, 2, 4])

In [51]:
a1[1] = 5
a1

array([1, 5, 4])

In [52]:
a

array([1, 5, 4])

In [55]:
a2 = a.copy()
a2

array([1, 5, 4])

In [56]:
a2[0] = 6
a2

array([6, 5, 4])

In [57]:
a

array([1, 5, 4])

In [58]:
c2

array([[0, 1, 2],
       [3, 4, 5]])