<a href="https://colab.research.google.com/github/YukiNoji3/SampleCode/blob/master/Python_DataAnalysis(NumPy)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**4.1.2 NumPyの概要**

In [0]:
import numpy as np
a = np.array([1, 2, 3])

In [80]:
a

array([1, 2, 3])

In [81]:
print(a)

[1 2 3]


In [82]:
type(a)

numpy.ndarray

In [83]:
a.shape

(3,)

In [0]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [85]:
b.shape

(2, 3)

In [86]:
type(b)

numpy.ndarray

In [87]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape(2, 3)
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [89]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [90]:
a.dtype

dtype('int64')

In [91]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [92]:
d.dtype

dtype('int16')

In [93]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [94]:
a

array([1, 2, 3])

In [95]:
a[0]

1

In [96]:
a[1:]

array([2, 3])

In [97]:
a[-1]

3

In [98]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
b[0]

array([1, 2, 3])

In [100]:
b[1, 0]

4

In [101]:
b[:, 2]

array([3, 6])

In [102]:
b[1, :]

array([4, 5, 6])

In [103]:
b[0, 1:]

array([2, 3])

In [104]:
b[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [105]:
a

array([1, 2, 3])

In [106]:
a[2] = 4
a

array([1, 2, 4])

In [107]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [109]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [110]:
a1 = a
a1

array([1, 2, 4])

In [111]:
a1[1] = 5
a1

array([1, 5, 4])

In [112]:
a

array([1, 5, 4])

In [113]:
a2 = a.copy()
a2

array([1, 5, 4])

In [114]:
a2[0] = 6
a2

array([6, 5, 4])

In [115]:
a

array([1, 5, 4])

In [116]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c3 = c2.ravel()
c4 = c2.flatten()

In [0]:
c3[0] =6
c4[1] =7

In [119]:
c4[1]

7

In [120]:
c3

array([6, 1, 2, 3, 4, 5])

In [121]:
c4

array([0, 7, 2, 3, 4, 5])

In [122]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [123]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [124]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array1[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [125]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [128]:
f = np.random.random((3, 2))
print(f)

[[0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]


In [129]:
print(f)

[[0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]


In [130]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [131]:
np.random.seed(123)
np.random.random((4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [132]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [133]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [134]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [135]:
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2, 3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [136]:
np.random.seed(123)
np.random.uniform(size=(4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [137]:
np.random.seed(123)
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [138]:
np.zeros(3)

array([0., 0., 0.])

In [139]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [140]:
np.ones(2)

array([1., 1.])

In [141]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [142]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [144]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [145]:
np.nan

nan

In [146]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [147]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [148]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [149]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [150]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [151]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [152]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [153]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [154]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [155]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

**4.1.3 NumPyの各機能**

In [158]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2,3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 11, 10)
print('a' , a)
print('b' , b)
print('c' , c)
print('d' , d)
print('e' , e)

a [0 1 2]
b [[-3 -2 -1]
 [ 0  1  2]]
c [[1 2 3]
 [4 5 6]]
d [[0 1]
 [2 3]
 [4 5]]
e [-1.          0.33333333  1.66666667  3.          4.33333333  5.66666667
  7.          8.33333333  9.66666667 11.        ]


In [160]:
print('a:', a.shape)
print('b:', b.shape)
print('c:', c.shape)
print('d:', d.shape)
print('e:', e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [0]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
  new.append([])
  for k in j:
    new[i].append(abs(k))

In [164]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [165]:
np.sin(e)

array([-0.84147098,  0.3271947 ,  0.99540796,  0.14112001, -0.9290145 ,
       -0.57819824,  0.6569866 ,  0.88729411, -0.23953677, -0.99999021])

In [166]:
np.cos(e)

array([ 0.54030231,  0.94495695, -0.09572355, -0.9899925 , -0.37004332,
        0.81589631,  0.75390225, -0.46120404, -0.97088729,  0.0044257 ])

In [167]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [168]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [169]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [170]:
a

array([0, 1, 2])

In [171]:
a + 10

array([10, 11, 12])

In [172]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [173]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [175]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [176]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [177]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [179]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [180]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [181]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [182]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [183]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [184]:
c / a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [185]:
c / (a + 1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [186]:
np.dot(b, a)

array([-4,  5])

In [187]:
b @ a

array([-4,  5])

In [188]:
a @ b

ValueError: ignored

In [189]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [190]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [191]:
a > 1

array([False, False,  True])

In [192]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [193]:
np.count_nonzero(b > 0)

2

In [194]:
np.sum(b > 0)

2

In [195]:
np.any(b > 0)

True

In [196]:
np.all(b > 0)

False

In [198]:
b[b > 0]

array([1, 2])

In [199]:
b == c

array([[False, False, False],
       [False, False, False]])

In [200]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [201]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [202]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [205]:
np.allclose(b, c)

False

In [206]:
np.allclose(b, c, atol=10)

True

In [207]:
np.sum(a)

3

In [208]:
a.sum()

3